
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

index_post_max: 10

copyright:
  author: John Doe
  begin_year: 2022
  end_year:  2025


icp_setting:
  enable : true
  icp: ""


gongan_setting:
  enable : true
  Icon_enanle: true
  Num: ""


# stylesheets loaded in the <head>
stylesheets:
- /css/Diamond.css

# scripts loaded in the end of the body
scripts:
- /js/Diamond.js
